print("="*80)
print("FINANCEBENCH RAG AGENT - ACCURACY COMPARISON")
print("="*80)

print("\n" + "-"*80)
print("PREVIOUS RESULTS (Before Migration)")
print("-"*80)
print("SDK: Claude Code SDK")
print("Date: 2025-09-22 (Earlier)")
print("Total Questions: 150 (reported in README)")
print("Accuracy: 86%")
print("Cost: $32.94 total ($0.22 per question)")
print("Notes: Using Claude Code SDK with markdown documents")

print("\n" + "-"*80)
print("CURRENT RESULTS (After Migration)")
print("-"*80)
print("SDK: Claude Agent SDK v0.1.0")
print("Date: 2025-09-30")
print("Total Questions: 150")
print("Correct: 124 (82.67%)")
print("Partial: 9 (6.00%)")
print("Incorrect: 17 (11.33%)")
print("Accuracy: 82.67%")
print("Cost: $13.64 total ($0.09 per question)")
print("Notes: Successfully migrated to Claude Agent SDK")

print("\n" + "="*80)
print("COMPARISON ANALYSIS")
print("="*80)

print("\nAccuracy Change:")
print(f"  Previous: 86.00%")
print(f"  Current:  82.67%")
print(f"  Difference: -3.33 percentage points")

print("\nCost Improvement:")
print(f"  Previous: $0.22 per question")
print(f"  Current:  $0.09 per question")
print(f"  Savings: 59% reduction in cost per question")
print(f"  Total savings: $19.30 (from $32.94 to $13.64)")

print("\n" + "-"*80)
print("KEY INSIGHTS")
print("-"*80)
print("1. Slight accuracy decrease (86% -> 82.67%, -3.33pp)")
print("2. Significant cost reduction (59% savings per question)")
print("3. Successfully migrated to Claude Agent SDK")
print("4. All 150 questions processed with only 1 error")
print("5. Documents correctly accessed from .finance/markdown/")

print("\n" + "-"*80)
print("POTENTIAL CAUSES FOR ACCURACY DIFFERENCE")
print("-"*80)
print("1. SDK migration may have slightly different system prompts")
print("2. Different default behaviors in Claude Agent SDK")
print("3. Potential changes in context management")
print("4. Could be within normal variance (need more runs to confirm)")

print("\n" + "-"*80)
print("RECOMMENDATIONS")
print("-"*80)
print("1. Review the 17 incorrect answers to identify patterns")
print("2. Fine-tune prompts for Claude Agent SDK")
print("3. Consider adjusting financial calculator thresholds")
print("4. Verify system prompt configuration in ClaudeAgentOptions")
print("5. Test with extended context or thinking mode if needed")

print("\n" + "="*80)
print("CONCLUSION")
print("="*80)
print("Migration successful with trade-offs:")
print("  [+] 59% cost reduction")
print("  [+] Successful SDK migration")
print("  [+] Access to new Agent SDK features (subagents, hooks)")
print("  [-] 3.33pp accuracy decrease (86% -> 82.67%)")
print("\nOverall: Good migration with opportunity to optimize prompts")
print("         to recover the 3-4% accuracy difference.")
print("="*80)